#mybatis的配置
#mybatis:
#  configuration:
    #   sql日志显示，这里使用标准显示
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #  数据库中如果有类似 如  user_name 等命名，会将 _后的字母大写，这里是为了和实体类对应
#    map-underscore-to-camel-case: true
  #  配置mapper文件的路径
#  mapper-locations: classpath:com/example/bookshare/*/mapper/*.xml,classpath:/mybaties/mapper/*.xml
  #pageHelper配置（官网推荐配置）
#pagehelper:
#  helperDialect: mysql
#  reasonable: true
#  supportMethodsArguments: true
#  params: count=countSql
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql


spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

mybatis-plus:
  mapper-locations: classpath:*/mapper/*.xml  #指定sql映射文件
#http://localhost:8160/doc.html